### ISSUE TITLE
Issue with PCF control on iOS

### ISSUE THREAD

**Issue by denhosi1** [rwilson504/nzcp-pcf#4]
Hi Rick,

We have implemented the PCF control on a Covid Sign In app we developed. The app has been working great; however, for the past few weeks it has stopped working on the device we have the app installed on. I am not sure if anything has changed in the way the NZ vaccine pass is read.

**Comment by rwilson504** [comment]
I believe the issue is caused by the app attempting to go out and get the issuer from the web.  In order to fix this, edit the application and set the offlineMode value in the NZCOVIDPass control to true.  Save and re-publish the application. This will utilize a cached version of the issuer information.

![image](https://user-images.githubusercontent.com/7444929/160148955-7d6b2e06-6baf-4af3-afb8-902c5e02d8e8.png)

**Comment by rwilson504** [comment]
@denhosi1 can you confirm this fixed the issue?

Thanks!

**Comment by denhosi1** [comment]
Hi @rwilson504 , Sorry, meant to get back to you sooner.  The fixed worked perfectly thank you. Cheers.
